[project]
name = "tidy-finance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyterlab>=4.5.1",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "tidyfinance>=0.2.5",
]
